In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.optimizers import Adam


In [ ]:
# Define the activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def tanh(x):
    return np.tanh(x)
def relu(x):
    return np.maximum(0, x)
def leaky_relu(x, alpha=0.01):
    return np.maximum(alpha * x, x)
def softmax(x):
    e_x=np.exp(x-np.max(x))
    return e_x/e_x.sum(axis=0)


In [ ]:
#Create a simple NN model with different activation

def create_model(activation):
  model=Sequential()
  model.add(Dense(64,activation=activation,kernel_regularizer=tf.keras.regularizers.l2(0.01)))
  model.add(Dense(32,activation=activation,kernel_regularizer=tf.keras.regularizers.l2(0.01)))
  model.add(Dense(1,activation='sigmoid'))
  model.compile(loss='binary_crossentropy',optimizer=Adam(learning_rate=0.001),metrics=['accuracy'])
  return model
  model.compile(loss='binary_crossentropy',optimizer=Adam(learning_rate=0.001),metrics=['accuracy'])
  return model

In [ ]:
#Generate the some data and split into training and testing test
X,y=make_blobs(n_samples=1000,n_features=2,random_state=42)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X,y

(array([[-6.59633932, -7.13901457],
        [-6.13753182, -6.58081701],
        [ 5.19820575,  2.04917508],
        ...,
        [ 3.69047995,  4.60555175],
        [ 4.03036663,  1.78619838],
        [-7.44179522, -7.08933147]]),
 array([2, 2, 1, 0, 0, 2, 1, 1, 1, 1, 0, 2, 0, 1, 1, 1, 0, 0, 0, 0, 1, 2,
        2, 2, 1, 0, 0, 0, 1, 1, 2, 2, 1, 0, 0, 2, 2, 1, 2, 2, 0, 1, 0, 2,
        0, 2, 0, 0, 2, 1, 2, 0, 1, 2, 0, 2, 0, 0, 0, 1, 1, 0, 2, 2, 0, 0,
        2, 1, 1, 0, 2, 0, 1, 1, 1, 2, 1, 0, 0, 0, 1, 0, 0, 0, 1, 2, 1, 2,
        0, 0, 0, 0, 1, 1, 2, 1, 2, 0, 1, 1, 1, 2, 2, 0, 2, 1, 1, 0, 1, 0,
        2, 1, 1, 1, 0, 1, 2, 2, 1, 0, 0, 1, 2, 1, 2, 2, 1, 2, 1, 1, 0, 1,
        1, 2, 0, 2, 0, 1, 1, 1, 0, 0, 2, 2, 2, 0, 1, 0, 0, 0, 0, 2, 1, 2,
        0, 1, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 1, 1, 2, 2, 1, 0, 0, 1, 0, 2,
        1, 2, 1, 2, 0, 1, 0, 1, 0, 2, 0, 2, 0, 2, 1, 0, 1, 1, 0, 2, 1, 1,
        1, 2, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 2, 2, 1, 1, 0, 2, 0, 2, 1,
        2, 2, 1, 0, 2, 0, 0, 

In [ ]:
#train the NN with different activation function
models={}
for activation in['sigmoid','tanh','relu','leaky_relu']:
  model=create_model(activation)
  model.fit(X_train,y_train,epochs=100,batch_size=32,verbose=0)
  y_pred=np.argmax(model.predict(X_test),axis=1)
  models[activation]=accuracy_score(y_test,y_pred)
  print(f'Accuracy with {activation} activation: {models[activation]}')

7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
Accuracy with sigmoid activation: 0.315
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step 
Accuracy with tanh activation: 0.315
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step 
Accuracy with relu activation: 0.315
7/7 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
Accuracy with leaky_relu activation: 0.315


In [9]:
import numpy as np
nparray = np.array([[1, 2, 3], [1, 4, 6],
                    [4, 3, 2]])
nparray


array([[1, 2, 3],
       [1, 4, 6],
       [4, 3, 2]])

In [10]:
r_sum = nparray.sum(axis = 0) #Row wise sum
r_sum

array([ 6,  9, 11])

In [11]:
c_sum = nparray.sum(axis = 1) #col wise sum
c_sum

array([ 6, 11,  9])